#!/bin/bash

conda activate func_anno "python=3.11" funannotate

############# FUNANNOTATE INSTALLATION #############

# setup funannotate databases
funannotate setup -b metazoa -d funannotate_DB/
export FUNANNOTATE_DB=/path/to/funannotate_DB/

# Download GeneMark-ES/ET/EP+ ver 4.71_lic and key from http://topaz.gatech.edu/GeneMark/license_download.cgi
tar -xf gmes_linux_64.tar.gz
mkdir gm_key
cp -r gm_key_64.gz gm_key/

# locate perl
which perl

# change all script perl tag from gmes folder 
cd gmes/
perl change_path_in_perl_scripts.pl 'perl PATH'

# set the path for GeneMark using 
export GENEMARK_PATH=$PWD/gmes/

# making sure that gmes_petap.pl in the PATH using 
export PATH=$PATH:$PWD/gmes/

######################################################

# Phobius (download from https://software.sbc.su.se/phobius.html)
phobius.pl -short aip.prot.fasta > Phar.phobius.results.txt

# InterProScan
funannotate iprscan -i aip.prot.fasta -m docker -c 50-o Aip_iprscan.xml

# eggnog-mapper
emapper.py --cpu 50 -m mmseqs --data_dir funannotate_DB  -i aip.prot.fasta -o Aip_eggnog

# # FUNANNOTATE ANNOTATE # #
funannotate annotate --gff aip.gff3 --fasta  /PATH/TO/aip_flye_raw/assembly.fasta -s "Exaiptasia diaphna" --busco_db  metazoa --eggnog Aip_eggnog.emapper.annotations --iprscan Aip_iprscan.xml --phobius phobius.results.txt --cpus 100 -o aip_anno

########## NCBI SUBMISSION ############ 

# this is only if you plan to submit to NCBI #
table2asn -M n -J -c w -euk -t Aip_ncbi.sbt -i /PATH/TO/aip_flye_raw/assembly.fasta -gaps-min 10 -l paired-ends -j "[organism=Exaiptasia diaphna] [isolate=F003]" -locus-tag-prefix ABFA07 -f aip.gff3 -o Aip.sqn -Z

#######################################


# # CHECK FINAL STATS # #
# this is generated by funannotate directly, but if you have done any manual curation of the gff3 file afterwards, you can run this again:
funannotate util stats -f /path/to/necat/PAG_Phar_UKon_1.1.fasta -g PAG_Phar_UKon_1.1.gff3 -o PAG_Phar_UKon_1.1.json
